"""
model_training.py
-----------------

Train a machine‑learning model to predict whether a vehicle requires maintenance based on
synthetic telemetry data.  The script loads a CSV file generated by `data_generator.py`,
splits the data into training and testing subsets, fits a random forest classifier
and evaluates its performance.  The trained model is saved to disk using joblib so
that it can be loaded by the Streamlit dashboard.

Usage:
    python model_training.py --data_path data/vehicle_telemetry.csv --model_path models/carcare_model.pkl

Dependencies are listed in `requirements.txt`.
"""

import argparse
from pathlib import Path
import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, ConfusionMatrixDisplay)
from sklearn.model_selection import train_test_split


def load_data(data_path: str) -> pd.DataFrame:
    """Load telemetry data from a CSV file."""
    df = pd.read_csv(data_path)
    return df


def train_model(X: pd.DataFrame, y: pd.Series, random_state: int = 42) -> RandomForestClassifier:
    """Train a random forest classifier on the provided features and target."""
    model = RandomForestClassifier(n_estimators=200, random_state=random_state, n_jobs=-1)
    model.fit(X, y)
    return model


def evaluate_model(model: RandomForestClassifier, X_test: pd.DataFrame, y_test: pd.Series) -> None:
    """Print evaluation metrics and display the confusion matrix."""
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {acc:.3f}\n")
    print("Classification report:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                  display_labels=['No Maintenance', 'Maintenance'])
    disp.plot(cmap='Blues')
    plt.title('Confusion Matrix')
    plt.tight_layout()
    # Ensure the images directory exists
    images_dir = Path('images')
    images_dir.mkdir(parents=True, exist_ok=True)
    fig_path = images_dir / 'confusion_matrix.png'
    plt.savefig(fig_path)
    plt.close()
    print(f"Confusion matrix saved to {fig_path}")


def save_model(model: RandomForestClassifier, model_path: str) -> None:
    """Persist the trained model to disk using joblib."""
    model_file = Path(model_path)
    model_file.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, model_file)
    print(f"Model saved to {model_file.resolve()}")


def parse_args() -> argparse.Namespace:
    """Parse command‑line arguments."""
    parser = argparse.ArgumentParser(description="Train a predictive maintenance model.")
    parser.add_argument('--data_path', type=str, default='data/vehicle_telemetry.csv',
                        help='Path to the CSV file containing telemetry data')
    parser.add_argument('--model_path', type=str, default='models/carcare_model.pkl',
                        help='Destination path to save the trained model')
    parser.add_argument('--test_size', type=float, default=0.3,
                        help='Proportion of data to use for testing (default: 0.3)')
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    df = load_data(args.data_path)
    X = df.drop(columns=['maintenance_needed'])
    y = df['maintenance_needed']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=42, stratify=y)

    model = train_model(X_train, y_train)
    evaluate_model(model, X_test, y_test)
    save_model(model, args.model_path)


if __name__ == '__main__':
    main()